### ISSUE TITLE
Julia Package Listing has no description for ExprRules

### ISSUE THREAD

**Issue by tawheeler** [sisl/ExprRules.jl#11]
![image](https://user-images.githubusercontent.com/3334079/33493375-b16d9602-d674-11e7-9580-a0c3bdb6d381.png)

**Comment by rcnlee** [comment]
Does it just pull from the tagline on the repo?  It's set there.  On the other hand, it worked for ExprOptimization.

**Comment by tawheeler** [comment]
Looks like it is working now.
