### ISSUE TITLE
Support Julia 0.7

### ISSUE THREAD

**Issue by tawheeler** [sisl/ExprRules.jl#13]
Would be nice for the package to update to support Julia 0.7.

**Comment by rcnlee** [comment]
Yeah, the whole ecosystem needs to be updated.  I can take this, but probably won't get to it until next week.

**Comment by tawheeler** [comment]
Looks like it requires TreeView, which in turn requires TikzGraphs, which in turn requires TikzPictures.
Turns out TikzPictures master is 0.7 compatable but there was no release, so I updated it to 0.7-beta2 and made a release.
Working on TikzGraphs next.

**Comment by tawheeler** [comment]
TikzPictures now in METADATA.
Submitted TikzGraphs

**Comment by tawheeler** [comment]
TikzGraphs release is in METADATA.
I made a PR for TreeView. The owner hasn't traditionally been very responsive...

**Comment by tawheeler** [comment]
Made a branch for the 07 fixes. Turns not not to require many changes.

**Comment by flare9x** [comment]
Looking forward to 0.7 updates!

**Comment by tawheeler** [comment]
Updates have been in for the last few weeks.
