### ISSUE TITLE
dot-broadcasting operators fail to populate symbol table

### ISSUE THREAD

**Issue by ancorso** [sisl/ExprRules.jl#18]
When trying to create a symbol table from a grammar with dot-broadcasting operators, those operators don't get included. This seems to be happening because the symbols don't show up in `Base` or `Main`. 

For a specific example, consider the grammar
```
grammar = @grammar begin
    R = u 
    R = R .* R 
end
```
Then the symbol table generated from 
```
SymbolTable(grammar)
```
is empty and 
```
isdefined(Main, :.*) == isdefined(Base,:.*) == false
```
this is with julia v1.0.3

**Comment by rcnlee** [comment]
I'm not sure where these elementwise operators are defined.  Are they remapped to call broadcast in the julia interpreter?  ``@which`` gives an ``UndefVar`` error, which suggests it might be internal.

The parse tree has the same form as a function, i.e., the head is ``call`` and ``arg[1]`` is ``.*``.

A workaround could be to avoid the dot operator by explicitly calling ``broadcast``.

**Comment by ancorso** [comment]
Thanks for looking into it! I don't know enough about julia to know how the dot is actually handled.

The workaround works for me -- it just makes my expressions slightly less pretty ;)

Feel free to rope someone in who might know more about this, or close it if you don't think its a big deal.

**Comment by rcnlee** [comment]
I'll take a closer look when I get back.

Some additional info:
https://discourse.julialang.org/t/elementwise-operators/19529/2

**Comment by jpsamaroo** [comment]
Dot-syntax is (usually?) handled by the parser and is lowered to calls to `Base.broadcasted` and `Base.materialize`:
```
julia> Meta.@lower 2 .* 3
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(*, 2, 3)
│   %2 = Base.materialize(%1)
└──      return %2
))))
```

**Comment by rcnlee** [comment]
ExprRules has a parser to determine the parts of the expressions.  I think it just needs to be updated to be able to handle this case explicitly.
