### ISSUE TITLE
Support non-`Symbol` LHS in `@grammar`?

### ISSUE THREAD

**Issue by jpsamaroo** [sisl/ExprRules.jl#20]
The example notebook shows the use of `Real` as the LHS for the initial grammar, which is intuitive both from the perspective of this package's functionality, as well as from the perspective of Julia syntax (i.e. any Julia user can look at a simple `@grammar` block and understand what's going on immediately).

Unfortunately, this nice symmetry breaks the moment you try to plug into `@grammar` a LHS like `Vector{Int}`, even though `Vector{Int}` is as much a type as `Real` is. While I could certainly do some string magic to normalize the type name to something like "Vector_Int", I feel like it would be beneficial to support specifying the LHS as an Expr directly.

I haven't spent much time digging into the internals of this package, but if the authors believe it's feasible, I'd be happy to take a stab at modifying `@grammar` to support this functionality.

**Comment by rcnlee** [comment]
Although we're using ``Real`` in the example, it's actually not interpreted as a type in the grammar at all.  It's a symbol that represents a non-terminal --- a symbol that is to be replaced if it is detected on the RHS.  It just so happens to correspond in this example.  Using a symbol on the LHS is quite natural and convenient for parsing and avoids a lot of ambiguities.  It's just a placeholder to be later replaced anyways, so it doesn't appear in the final expressions.  What benefit do you expect to gain from allowing Exprs and actual types on the LHS?  Is it just syntactic sugar?

**Comment by jpsamaroo** [comment]
It's really just syntactic sugar in the end, but given Julia's type-driven design, it just feels natural to me to be able to use types as non-terminals for my usecase. Because the RHS of grammars "lower" to `Expr`s (via `get_executable`), which are then fed into type inference with fixed argument types, I expected that I could re-use types in grammars to model the same interaction at the grammar level (essentially matching the method I want to dispatch to when I actually execute the resulting `Expr`).

But I can understand that this isn't necessarily easy to implement (or guaranteed to always work). If you don't think this is desirable, I can certainly find a way to do the "Julia types -> Non-terminal symbol" in my package :slightly_smiling_face:

**Comment by rcnlee** [comment]
Yeah, both of those.  I think this will introduce a lot of complications and subtle issues if LHS can be more than symbols.  Not worth pursuing IMHO.
