### ISSUE TITLE
Add/document function to merge Grammars

### ISSUE THREAD

**Issue by jpsamaroo** [sisl/ExprRules.jl#21]
I'd like to be able to specify grammars separately, which may use some or all of the same non-terminals, and then be able to merge the grammars into a new, combined grammar. I haven't been able to find a function which can support this so far.

Motivation: I'm developing a package to generate Flux.jl neural network models from an ExprRules grammar by using ExprOptimization. My package implements a package-global grammar which contains some rules for composing various Flux layers and Base functions. I would like to be able to add more rules to this table at runtime by loading external packages, which will re-use some of the same non-terminals to provide composability. Having the ability to merge two or more grammars into a single grammar would give me the ability to extend my package-global grammar just like we extend method tables by loading packages in Julia.

**Comment by rcnlee** [comment]
I think this can be implemented fairly easily by concatenating most of the fields of the grammar struct together to create the combined grammar.  

I put together a prototype and pushed it to the master branch.  I added a function ``append!(grammar1, grammar2)`` which will append the production rules of grammar2 to grammar1.  Can you see if that will meet your needs?

**Comment by jpsamaroo** [comment]
This worked well for me, with one change (to prevent accidental sharing):

```diff
diff --git a/src/ExprRules.jl b/src/ExprRules.jl
index 3e96f29..b100148 100644
--- a/src/ExprRules.jl
+++ b/src/ExprRules.jl
@@ -162,7 +162,7 @@ function Base.append!(grammar1::Grammar, grammar2::Grammar)
     append!(grammar1.types, grammar2.types)
     append!(grammar1.isterminal, grammar2.isterminal)
     append!(grammar1.iseval, grammar2.iseval)
-    append!(grammar1.childtypes, grammar2.childtypes)
+    append!(grammar1.childtypes, copy.(grammar2.childtypes))
     for (s,v) in grammar2.bytype
         grammar1.bytype[s] = append!(get(grammar1.bytype, s, Int[]), N .+ v)
     end
```

**Comment by rcnlee** [comment]
Good point!  I updated it on master and pushed.
