### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by AStupidBear** [sisl/ExprRules.jl#26]
Since a lot of changes have been commited, should a new release be tagged?

**Comment by mykelk** [comment]
Good idea. To facilitate automatic merging, I think we need to specify the compatibility limits in the Project.toml. @rcnlee do you want to take care of that?

**Comment by rcnlee** [comment]
How do you do that? How do I determine the range fo compatibility of the deps? and then how do I include it in the Project.toml?

**Comment by mykelk** [comment]
Probably the best way is to use this: https://github.com/JuliaRegistries/CompatHelper.jl
Alternatively, you can just specify what you have tested on.

**Comment by rcnlee** [comment]
Done! Just tagged a release.  I put my testing setup into the compat of the Project.toml.  It's pretty recent.  Hopefully it's not too restrictive.

**Comment by AStupidBear** [comment]
@rcnlee How about registering a new version in https://github.com/JuliaRegistries/General?

**Comment by rcnlee** [comment]
@mykelk Hmm... do I have admin on this repo? I don't see the Settings button.  I remember webhooks used to be set up on here at one point and updating the registry was automatic.  Want to check the settings.  Thanks!

**Comment by rcnlee** [comment]
@mykelk Are we good to go to register and release?

**Comment by mykelk** [comment]
Yep! I'll take care of it now.
