### ISSUE TITLE
heirarchical types don't work

### ISSUE THREAD

**Issue by tawheeler** [sisl/ExprRules.jl#3]
For some reason this fails:

```
ruleset = @ruleset begin
    R = I
    I = 1
end

rulenode = RuleNode(1, [RuleNode(2)])
get_executable(rulenode, ruleset)
```

Will add to runtests.jl

**Comment by rcnlee** [comment]
_get_executable incorrectly assumes that the RHS is an Expr.  Added a case for symbols.

Fixed by 50677a72149c0c615f638ca61063b2b6069b53b0
