### ISSUE TITLE
Operator with coefficients

### ISSUE THREAD

**Issue by cobac** [sisl/ExprRules.jl#32]
Hello.

For our application we want to implement a linear operator `f(x, a, b) = a + b*x`.
We want this operator node to only have one children `Real = f(Real)`,
but we need to access and modify the values of the coefficients.

We've tried hacking around with the `_val` field without luck.
We can't think of a way of achieving this without modifying `ExprRules.jl` source code, but we wanted to post this issue first in case we are missing something.
We'll appreciate any input about how to go to implement this with or without modifying your source code.

Thank you!

**Comment by rcnlee** [comment]
Hi @cobac,
Am I correct in saying that you want to set values `a` and `b` externally and have `x` be the non-terminal `Real` in `f(Real)` that is optimized by EO?  If that's the case, it is very similar to the symbolic regression example [here](https://github.com/sisl/ExprOptimization.jl/blob/master/examples/symbolic_regression.ipynb) except that the parameters and the variables are reversed (the example optimizes `a` and `b` and sets `x`).  You can put arbitrary terminal symbols into expressions.  (If the symbols don't appear on the left-hand side of any rules, they are considered terminal.)  Then set the value of those variables into the symbol table before you call evaluate.

**Comment by cobac** [comment]
Hey, thank you for your reply. Sorry for not being very clear.

> Am I correct in saying that you want to set values a and b externally and have x be the non-terminal Real in f(Real) that is optimized by ExprOptimization?

No. In this case we are implementing our own symbolic regression algorithm. 

We want to implement an operator node `Real = f(Real)`  with only one child (terminal or not). However, a tree could contain multiple nodes of this type, each of them parametrized with a different `a` and `b` that we set/optimize externally.

**Comment by rcnlee** [comment]
It sounds like you want the function f to somehow store mutable parameters a and b, but ultimately only take one argument when evaluated.  ExprRules.jl can actually work with any julia type, including custom structs.  I think a custom struct, combined with _val might do what you want.

```
mutable struct F
  a
  b
end
F() = F(1,1)

function f(p::F, x)
  p.a + p.b * x
end

grammar = @grammar begin
  Params = _(F())
  Real = x | f(Params,Real)
end

rulenode = RuleNode(3, [RuleNode(1, F()), RuleNode(2)])  # should also behave properly under rand()
@show rulenode.children[1]._val  #is mutable, set a and b here
```

**Comment by cobac** [comment]
>  ExprRules.jl can actually work with any julia type
> [...] 
>  Params = _(F())
> Real = x | f(Params,Real)

Oooh, hadn't thought of this. I had already started working on implementing a custom node type, making `RuleNode <: AbstractNode` and modifying ExprRules.jl to work with both types of nodes. But your suggestion looks very promising. I will test it tomorrow and report back.

Thanks a lot!

**Comment by cobac** [comment]
So, I think your suggestion is the way to go. I've run into one obstacle that I've been able to solve not-very-elegantly. If you have any suggestion to circumvent it I'll be happy to hear it. If not, we can close this issue :)

I'm defining my grammar inside the scope of a package module. However, at evaluation time the expression must be evaluated out of its scope since I get `F() is not defined`. I've circumvented it by including the prefix of my package in the grammar

```julia
grammar = @grammar begin
  Params = _(MyPackage.F())
  Real = x | f(Params,Real)
end
```
However, ideally I'd like to initialize the coefficients by drawing them from some distribution parametrized only at runtime (i.e. `d` only is created at runtime).

```julia
F(d) = F(rand(Prior_a(d)), rand(Prior_b(d)))
function mygrammar(d)
    grammar = @grammar begin
        Params = _(MyPackage.F(d))
        Real = x | f(Params,Real)
    return grammar
    end
end 
```

However, similarly to the first code block I get `d is not defined`.

What I'm doing currently is initializing everything with `F(0,0)` and then iterating over the tree and modifying the coefficients. This is not the end of the world because I have to iterate over the tree either way as part of the algorithm, but it still feels ugly.

**Comment by rcnlee** [comment]
The expression inside _() is actually being evaluated at Main scope, so you could define it there and it would work.  I don't think there is a way to evaluate it using the function local scope.  

One idea is to use a global variable scoped to your package:

```julia
module MyPackage

using ExprRules

mutable struct F
    a
    b
end
F() = F(1,1)
F(d) = F(rand(d), rand(d))

d = 0
function mygrammar(d_in)
    global d = d_in
    grammar = @grammar begin
        Params = _(MyPackage.F(MyPackage.d))
        Real = x | f(Params,Real)
    return grammar
    end
end 
end #module

b = 100:200
g = MyPackage.mygrammar(b)
node = rand(RuleNode, g, :Params)
node._val
```

**Comment by cobac** [comment]
Great, thank you again.
