### ISSUE TITLE
Project.toml needs to allow TreeView 0.5.0 due to LightGraphs -> Graphs change

### ISSUE THREAD

**Issue by elsoroka** [sisl/ExprRules.jl#36]
LightGraphs changed to Graphs, which caused TikzGraphs to update which [caused TreeView to update](https://github.com/JuliaTeX/TreeView.jl/pull/32). TreeView 0.4.0 uses LightGraphs and 0.5.0 uses Graphs.

However, ExprRules.jl Project.toml requires TreeView 0.4.0. So in ExprOptimization, the `display` method crashes with errors like `MethodError: no method matching plot(::LightGraphs.SimpleGraphs.SimpleDiGraph{Int64}; layout::TikzGraphs.Layouts.Layered, labels::Vector{String})`

I successfully fixed this on my machine using Julia 1.10.0 by installing ExprRules.jl in develop mode and modifying the ExprRules Project.toml to require TreeView 0.5.0.

**Comment by mykelk** [comment]
Great! Feel free to file a PR and we'll get it merged! Thanks!

**Comment by elsoroka** [comment]
Thank you! I tried to push a branch but I didn't have permission. (I don't know how to make a PR.) have tried to google but the results are drowned in "how to use Git UI" and I use the command line

**Comment by mykelk** [comment]
Feel free to email me a link to a zipped file. Thanks!

**Comment by elsoroka** [comment]
I figured it out by inspecting old PRs, sorry
