### ISSUE TITLE
`walk_tree` fails on non-expressions

### ISSUE THREAD

**Issue by tawheeler** [sisl/ExprRules.jl#4]
`display()` will fail if called on an expression that is just, say, 1.

**Comment by rcnlee** [comment]
Can you provide some code to recreate the problem?
It seems to work for me because of the ``if`` statement in ``Base.display``.
```julia
function Base.display(rulenode::RuleNode, ruleset::RuleSet)
    root = get_executable(rulenode, ruleset)
    if isa(root, Expr)
        walk_tree(root)
    else
        root
    end
end
```

**Comment by tawheeler** [comment]
Hmm... have to see how I got this error then
