### ISSUE TITLE
Organization of packages

### ISSUE THREAD

**Issue by rcnlee** [sisl/ExprRules.jl#6]
I'd like to start adding other optimization algorithms to the ExprOptimization package.  There are two fundamental capabilities that need to be implemented.
1. A probabilistic model that sits on top of the grammar, as in PCFGs.  (i.e., CE method uses this)
1. Sequentialization of the decisions of the tree to make it appear as an MDP.  (i.e., GE and MCTS use this)

These functions are reusable pieces that may be common to multiple algorithms.  Where should we put them?  Some options:
1. Into their own packages.
1. Into ExprRules
1. As submodules in ExprOptimization

Thoughts/preferences?

**Comment by mykelk** [comment]
Perhaps add a package called ProbabilisticExprRules? The sequentialization should probably go into submodules in ExprOptimization.

**Comment by tawheeler** [comment]
Our expression optimization has some things implemented for both probabilistic models and sequentialization if you need (unoptimized) code snippets.
I agree that the probabilistic model is algorithm dependent and probably needs to be in the optimization chapter. 
Not sure how many ways there are to construct `RuleNode`s from integer vectors --- if it is really standard we can put it in `ExprRules`. Something like MCTS probably needs more complicated data types though.

**Comment by rcnlee** [comment]
Are all the code snippets in the chapter? or are there more in the form of ipynb?

**Comment by tawheeler** [comment]
None in the form of ipynb.
Some code snippets are embedded in the LaTeX code to generate the figures though. I can share that with you.

**Comment by rcnlee** [comment]
Thanks!
