### ISSUE TITLE
remove `::Type{RuleNode}` from rand

### ISSUE THREAD

**Issue by tawheeler** [sisl/ExprRules.jl#7]
The current function signature is:
`rand(::Type{RuleNode}, ruleset::RuleSet, typ::Symbol, max_depth::Int=10)`

For brevity, since we are already using the `RuleSet` type, can we change it to:

`rand(ruleset::RuleSet, typ::Symbol, max_depth::Int=10)`?

**Comment by mykelk** [comment]
True. But isn't the convention for `rand` to include the type in the first argument? Of course, it's not strictly necessary. I'm okay either way, personally, but I wanted to ask about it.

**Comment by rcnlee** [comment]
I have a slight preference for keeping with convention in case we want to generate other random output types from the grammar.  e.g., if you didn't care about the derivation tree and just wanted Exprs, you could do ``rand(Expr, ruleset, typ)``.

**Comment by mykelk** [comment]
Agreed.
