### ISSUE TITLE
Handling _() functions in the grammar

### ISSUE THREAD

**Issue by rcnlee** [sisl/ExprRules.jl#9]
Currently, algorithm developers have to explicitly check for and handle the special case of _() when creating rulenodes if they want to construct rulenodes manually, like this:
```
    rulenode = grammar.iseval[rule_index] ?
        RuleNode(rule_index, eval(Main, grammar.rules[rule_index].args[2])) :
        RuleNode(rule_index)
```
(If they just call ``rand()``, then they don't need to do this). The second argument calls _() and concretizes the value into the node.  

I think a cleaner way to do this is to include the check in the constructor of RuleNode.  However, this would require passing ``grammar`` as an argument to RuleNode() and change the API.

Thoughts?

**Comment by tawheeler** [comment]
I like being able to call `RuleNode(integer)`
Wouldn't be against adding additional constructors.

**Comment by rcnlee** [comment]
I agree, that's quite convenient.  I'll add another constructor as suggested.
